add wave -position end  sim:/Complete_MIPS/clk_blah
add wave -position end  sim:/Complete_MIPS/reset
add wave -position end  sim:/Complete_MIPS/ADDR
add wave -position end  sim:/Complete_MIPS/CPU/format
add wave -position end  sim:/Complete_MIPS/CPU/instr
add wave -position end  sim:/Complete_MIPS/CPU/pc
add wave -position end  sim:/Complete_MIPS/CPU/npc
add wave -position end  sim:/Complete_MIPS/CPU/state
add wave -position end  sim:/Complete_MIPS/CPU/nstate
add wave -position end  sim:/Complete_MIPS/CPU/imm_ext
add wave -position end  sim:/Complete_MIPS/CPU/alu_result
add wave -position end  sim:/Complete_MIPS/CPU/opsave
add wave -position end  sim:/Complete_MIPS/CPU/alu_result_save
add wave -position end  sim:/Complete_MIPS/CPU/regw
add wave -position end  sim:/Complete_MIPS/CPU/dr
add wave -position end  sim:/Complete_MIPS/CPU/Register/DR
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[1]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[2]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[3]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[4]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[5]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[6]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[7]
add wave -position end  sim:/Complete_MIPS/CPU/Register/REG[8]